from pydantic import BaseModel, Field
from typing import Optional



class PaymentOrderRequestSchema(BaseModel):
    amount: float = Field(..., description="Amount to be paid")
    currency: str = Field(default="INR", description="Currency code, e.g., 'INR'")


class PaymentOrderResponseSchema(BaseModel):
    order_id: str = Field(..., description="Unique identifier for the payment order")
    amount: int = Field(..., description="Amount requested from frontend")


class PaymentVerificationRequestSchema(BaseModel):
    razorpay_order_id: str = Field(..., description="Razorpay order id (same generated from backend)")
    razorpay_payment_id: str = Field(..., description="Unique payment id for each payment")
    razorpay_signature: str = Field(..., description="Unique signature/hash generated by razorpay for each payment")

class PaymentVerificationResponseSchema(BaseModel):
    success: bool = Field(..., description="Whether payment verification succeeded")
    message: str = Field(..., description="Human readable message for frontend")

    order_id: Optional[str] = Field(
        None,
        description="Razorpay order id"
    )
    payment_id: Optional[str] = Field(
        None,
        description="Razorpay payment id"
    )